server:
  port: 8109
spring:
  application:
    name: nacos-client-a
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: ef27b2f3-9759-43cf-b02e-097bf622c493
        group: A-GROUP
